DROP TABLE IF EXISTS content;
CREATE TABLE content (
  id int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  value text NOT NULL,
  language varchar(2) NOT NULL DEFAULT 'en',
  state varchar(25) NOT NULL DEFAULT 'Active',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO content (id, name, value, language, state) VALUES
(1, 'Site.language', 'en', 'en', 'Active'),
(2, 'Site.title', 'MakingDevelopers', 'en', 'Active'),
(3, 'Site.meta.abstract', 'Learn to code', 'en', 'Active'),
(4, 'Site.meta.description', 'Learn to code', 'en', 'Active'),
(5, 'Site.meta.keywords', 'HTML5, JavaScript, Node.js', 'en', 'Active'),
(6, 'Site.language', 'es', 'es', 'Active'),
(7, 'Site.title', 'MakingDevelopers', 'es', 'Active'),
(8, 'Site.meta.abstract', 'Aprende a programar', 'es', 'Active'),
(9, 'Site.meta.description', 'Aprende a programar', 'es', 'Active'),
(10, 'Site.meta.keywords', 'HTML5, JavaScript, Node.js', 'es', 'Active'),
(11, 'Dashboard.forms.fields.activeComments', 'Active Comments?', 'en', 'Active'),
(12, 'Dashboard.forms.fields.author', 'Author', 'en', 'Active'),
(13, 'Dashboard.forms.fields.codes', 'Codes', 'en', 'Active'),
(14, 'Dashboard.forms.fields.content', 'Content', 'en', 'Active'),
(15, 'Dashboard.forms.fields.excerpt', 'Excerpt', 'en', 'Active'),
(16, 'Dashboard.forms.fields.language', 'Language', 'en', 'Active'),
(17, 'Dashboard.forms.fields.save', 'Save', 'en', 'Active'),
(18, 'Dashboard.forms.fields.selects.decision', '1:Yes|0:No', 'en', 'Active'),
(19, 'Dashboard.forms.fields.selects.languages', 'en:English|es:Spanish', 'en', 'Active'),
(20, 'Dashboard.forms.fields.selects.state', 'Active:Active|Inactive:Inactive', 'en', 'Active'),
(21, 'Dashboard.forms.fields.slug', 'Friendly URL', 'en', 'Active'),
(22, 'Dashboard.forms.fields.state', 'State', 'en', 'Active'),
(23, 'Dashboard.forms.fields.tags', 'Tags', 'en', 'Active'),
(24, 'Dashboard.forms.fields.title', 'Title', 'en', 'Active'),
(25, 'Dashboard.modules.dashboard.name', 'Dashboard', 'en', 'Active'),
(26, 'Dashboard.modules.blog.name', 'Blog', 'en', 'Active'),
(27, 'Dashboard.modules.blog.action', 'Add new post', 'en', 'Active'),
(28, 'Dashboard.modules.config.name', 'Configuration', 'en', 'Active'),
(29, 'Dashboard.modules.feedback.name', 'Feedback', 'en', 'Active'),
(30, 'Dashboard.modules.users.name', 'Users', 'en', 'Active'),
(31, 'Dashboard.modules.logout.name', 'Logout', 'en', 'Active'),
(32, 'Users.register.success', 'Your account have been created correctly, enjoy our site!', 'en', 'Active'),
(33, 'Users.register.fail', 'There was a problem trying to create your account, please try again.', 'en', 'Active'),
(34, 'Db.errors.exists:username', 'The username already exists', 'en', 'Active'),
(35, 'Db.errors.exists:email', 'The email is already registered', 'en', 'Active'),
(36, 'Db.errors.exists:social:networkId', 'This social user already exists', 'en', 'Active'),
(37, 'Db.errors.invalid:email', 'Invalid Email', 'en', 'Active'),
(38, 'Db.errors.invalid:number:subscribed', 'Subscribed should be 1 or 0', 'en', 'Active'),
(39, 'Db.errors.undefined:avatar', 'Avatar is undefined', 'en', 'Active'),
(40, 'Db.errors.undefined:networkId', 'NetworkId is undefined', 'en', 'Active'),
(41, 'Db.errors.undefined:username', 'Username is undefined', 'en', 'Active'),
(42, 'Db.success.inserted:website:username', 'User created successfuly', 'en', 'Active'),
(43, 'Db.success.inserted:social:username', 'Social User created successfuly', 'en', 'Active'),
(44, 'Dashboard.forms.fields.activeComments', '¿Activar Comentarios?', 'es', 'Active'),
(45, 'Dashboard.forms.fields.author', 'Autor', 'es', 'Active'),
(46, 'Dashboard.forms.fields.codes', 'Códigos', 'es', 'Active'),
(47, 'Dashboard.forms.fields.content', 'Contenido', 'es', 'Active'),
(48, 'Dashboard.forms.fields.excerpt', 'Extracto', 'es', 'Active'),
(49, 'Dashboard.forms.fields.language', 'Idioma', 'es', 'Active'),
(50, 'Dashboard.forms.fields.save', 'Guardar', 'es', 'Active'),
(51, 'Dashboard.forms.fields.selects.decision', '1:Si|0:No', 'es', 'Active'),
(52, 'Dashboard.forms.fields.selects.languages', 'en:Inglés|es:Español', 'es', 'Active'),
(53, 'Dashboard.forms.fields.selects.state', 'Active:Activo|Inactive:Inactivo', 'es', 'Active'),
(54, 'Dashboard.forms.fields.slug', 'URL Amigable', 'es', 'Active'),
(55, 'Dashboard.forms.fields.state', 'Estado', 'es', 'Active'),
(56, 'Dashboard.forms.fields.tags', 'Etiquetas', 'es', 'Active'),
(57, 'Dashboard.forms.fields.title', 'Título', 'es', 'Active'),
(58, 'Dashboard.modules.blog.action', 'Agregar nueva publicación', 'es', 'Active'),
(59, 'Dashboard.modules.blog.name', 'Blog', 'es', 'Active'),
(60, 'Dashboard.modules.config.name', 'Configuración', 'es', 'Active'),
(61, 'Dashboard.modules.dashboard.name', 'Dashboard', 'es', 'Active'),
(62, 'Dashboard.modules.feedback.name', 'Contacto', 'es', 'Active'),
(63, 'Dashboard.modules.logout.name', 'Desconectar', 'es', 'Active'),
(64, 'Dashboard.modules.users.name', 'Usuarios', 'es', 'Active'),
(65, 'Db.errors.exists:email', 'El correo electrónico ya está registrado', 'es', 'Active'),
(66, 'Db.errors.exists:social:networkId', 'Este usuario social ya existe', 'es', 'Active'),
(67, 'Db.errors.exists:username', 'El usuario ya existe', 'es', 'Active'),
(68, 'Db.errors.invalid:email', 'Email Inválido', 'es', 'Active'),
(69, 'Db.errors.invalid:number:subscribed', 'El campo Subscribed debe ser 1 o 0', 'es', 'Active'),
(70, 'Db.errors.undefined:avatar', 'El avatar no esta definido', 'es', 'Active'),
(71, 'Db.errors.undefined:networkId', 'El NetworkId no está definido', 'es', 'Active'),
(72, 'Db.errors.undefined:username', 'El Usuario no está definido', 'es', 'Active'),
(73, 'Db.success.inserted:social:username', 'Usuario social creado exitosamente', 'es', 'Active'),
(74, 'Db.success.inserted:website:username', 'Usuario creado exitosamente', 'es', 'Active'),
(75, 'Users.register.fail', 'Hubo un error al intentar crear tu cuenta, por favor intenta más tarde.', 'es', 'Active'),
(76, 'Users.register.success', '¡Tu cuenta ha sido creada exitosamente, disfruta nuestro sitio!', 'es', 'Active'),
(77, 'Dashboard.modules.blog.messages.add.success', 'The post was created correctly', 'en', 'Active'),
(78, 'Dashboard.modules.blog.messages.add.fail', 'There was a problem trying to create the post', 'en', 'Active'),
(79, 'Dashboard.modules.blog.messages.add.success', 'La publicación fue creada exitosamente', 'es', 'Active'),
(80, 'Dashboard.modules.blog.messages.add.fail', 'Hubo un problema al intentar crear la publicación', 'es', 'Active'),
(81, 'Dashboard.modules.blog.messages.add.exists', 'The post already exists', 'en', 'Active'),
(82, 'Dashboard.modules.blog.messages.add.exists', 'La publicación ya existe', 'es', 'Active'),
(83, 'Users.email.label', 'Email', 'en', 'Active'),
(84, 'Users.email.label', 'Correo electrónico', 'es', 'Active'),
(85, 'Users.subscribe', 'Subscribe', 'en', 'Active'),
(86, 'Users.subscribe', 'Suscribirme', 'es', 'Active'),
(87, 'Users.register.label', 'Register', 'en', 'Active'),
(88, 'Users.register.label', 'Registrar', 'es', 'Active'),
(89, 'Users.email.placeholder', 'email@example.com', 'en', 'Active'),
(90, 'Users.email.placeholder', 'email@dominio.com', 'es', 'Active'),
(91, 'Users.hello', 'Hello', 'en', 'Active'),
(92, 'Users.hello', 'Hola', 'es', 'Active'),
(93, 'Site.errors.error404', 'Error 404: Página no encontrada', 'es', 'Active'),
(94, 'Site.errors.error404', 'Error 404: Page Not Found', 'en', 'Active'),
(95, 'Dashboard.forms.fields.error.title', 'You need to write a title', 'en', 'Active'),
(96, 'Dashboard.forms.fields.error.title', 'Necesitas escribir un título', 'es', 'Active'),
(97, 'Dashboard.forms.fields.error.slug', 'The friendly url is missing', 'en', 'Active'),
(98, 'Dashboard.forms.fields.error.slug', 'La URL amigable es obligatoria', 'es', 'Active'),
(99, 'Dashboard.forms.fields.error.excerpt', 'The excerpt is missing', 'en', 'Active'),
(100, 'Dashboard.forms.fields.error.excerpt', 'El abstracto es obligatorio', 'es', 'Active'),
(101, 'Dashboard.forms.fields.error.content', 'Write some content', 'en', 'Active'),
(102, 'Dashboard.forms.fields.error.content', 'Escribe algún contenido', 'es', 'Active'),
(103, 'Dashboard.forms.fields.error.author', 'Who is writing this post?', 'en', 'Active'),
(104, 'Dashboard.forms.fields.error.author', '¿Quién está escribiendo esta publicación?', 'es', 'Active'),
(105, 'Dashboard.table.action', 'Action', 'en', 'Active'),
(106, 'Dashboard.table.action', 'Acción', 'es', 'Active'),
(107, 'Dashboard.table.title', 'Title', 'en', 'Active'),
(108, 'Dashboard.table.title', 'Título', 'es', 'Active'),
(109, 'Dashboard.table.author', 'Author', 'en', 'Active'),
(110, 'Dashboard.table.author', 'Autor', 'es', 'Active'),
(111, 'Dashboard.table.state', 'State', 'en', 'Active'),
(112, 'Dashboard.table.state', 'Estado', 'es', 'Active'),
(113, 'Dashboard.table.id', 'ID', 'en', 'Active'),
(114, 'Dashboard.table.id', 'ID', 'es', 'Active'),
(115, 'Dashboard.table.pending', 'Pending', 'en', 'Active'),
(116, 'Dashboard.table.pending', 'Pendiente', 'es', 'Active'),
(117, 'Dashboard.table.deleted', 'Deleted', 'en', 'Active'),
(118, 'Dashboard.table.deleted', 'Eliminado', 'es', 'Active'),
(119, 'Dashboard.table.inactive', 'Inactive', 'en', 'Active'),
(120, 'Dashboard.table.inactive', 'Borrador', 'es', 'Active'),
(121, 'Dashboard.table.active', 'Active', 'en', 'Active'),
(122, 'Dashboard.table.active', 'Publicado', 'es', 'Active'),
(123, 'Dashboard.modules.blog.list', 'List of Posts', 'en', 'Active'),
(124, 'Dashboard.modules.blog.list', 'Lista de Publicaciones', 'es', 'Active'),
(125, 'Dashboard.modules.blog.create', 'Create New Post', 'en', 'Active'),
(126, 'Dashboard.modules.blog.create', 'Crear Nueva Publicación', 'es', 'Active'),
(127, 'Dashboard.table.edit', 'Edit', 'en', 'Active'),
(128, 'Dashboard.table.edit', 'Editar', 'es', 'Active'),
(129, 'Dashboard.table.delete', 'Delete', 'en', 'Active'),
(130, 'Dashboard.table.delete', 'Eliminar', 'es', 'Active'),
(131, 'Dashboard.table.restore', 'Restore', 'en', 'Active'),
(132, 'Dashboard.table.restore', 'Restaurar', 'es', 'Active'),
(133, 'Dashboard.modules.blog.messages.update.fail', 'There was a problem trying to update the post', 'en', 'Active'),
(134, 'Dashboard.modules.blog.messages.update.fail', 'Hubo un problema al intentar actualizar la publicación', 'es', 'Active'),
(135, 'Dashboard.modules.blog.messages.update.success', 'The post was updated correctly', 'en', 'Active'),
(136, 'Dashboard.modules.blog.messages.update.success', 'La publicación fue actualizada correctamente', 'es', 'Active'),
(137, 'Dashboard.forms.fields.edit', 'Edit', 'en', 'Active'),
(138, 'Dashboard.forms.fields.edit', 'Editar', 'es', 'Active'),
(139, 'Dashboard.table.noData', 'No Data Found', 'en', 'Active'),
(140, 'Dashboard.table.noData', 'No hay elementos para mostrar', 'es', 'Active'),
(141, 'Dashboard.search.searching', 'Searching', 'en', 'Active'),
(142, 'Dashboard.search.searching', 'Buscando', 'es', 'Active'),
(143, 'Dashboard.search.label', 'Search', 'en', 'Active'),
(144, 'Dashboard.search.label', 'Buscar', 'es', 'Active'),
(145, 'Dashboard.search.placeholder', 'Type your search...', 'en', 'Active'),
(146, 'Dashboard.search.placeholder', 'Escribe tu búsqueda...', 'es', 'Active'),
(147, 'Dashboard.table.remove', 'Remove', 'en', 'Active'),
(148, 'Dashboard.table.remove', 'Remover', 'es', 'Active'),
(149, 'Dashboard.table.actions.delete.question', 'Do you want to send these records to the trash?', 'en', 'Active'),
(150, 'Dashboard.table.actions.delete.question', '¿Deseas enviar estos registros a la papelera?', 'es', 'Active'),
(151, 'Dashboard.table.actions.remove.question', 'Do you want to remove permanently these records?', 'en', 'Active'),
(152, 'Dashboard.table.actions.remove.question', '¿Deseas eliminar permanentemente estos registros?', 'es', 'Active'),
(153, 'Dashboard.table.actions.restore.question', 'Do you want to restore these records?', 'en', 'Active'),
(154, 'Dashboard.table.actions.restore.question', '¿Deseas recuperar estos registros?', 'es', 'Active'),
(155, 'Api.errors.noData', 'No data found', 'en', 'Active'),
(156, 'Api.errors.noData', 'No hay información para mostrar', 'es', 'Active'),
(157, 'Api.errors.invalidMethod', 'Invalid Method', 'en', 'Active'),
(158, 'Api.errors.invalidMethod', 'Método Inválido', 'es', 'Active'),
(159, 'Dashboard.media.upload.submit', 'Upload', 'en', 'Active'),
(160, 'Dashboard.media.upload.submit', 'Subir', 'es', 'Active'),
(161, 'Dashboard.media.upload.search.placeholder', 'Search files...', 'en', 'Active'),
(162, 'Dashboard.media.upload.search.placeholder', 'Buscar archivos...', 'es', 'Active'),
(163, 'Dashboard.media.insert', 'Insert', 'en', 'Active'),
(164, 'Dashboard.media.insert', 'Insertar', 'es', 'Active'),
(165, 'Dashboard.media.download', 'Download', 'en', 'Active'),
(166, 'Dashboard.media.download', 'Descargar', 'es', 'Active'),
(167, 'Dashboard.media.close', 'Close Media', 'en', 'Active'),
(168, 'Dashboard.media.close', 'Cerrar Media', 'es', 'Active'),
(169, 'Dashboard.media.title', 'Media', 'en', 'Active'),
(170, 'Dashboard.media.title', 'Media', 'es', 'Active'),
(171, 'Dashboard.modules.content.name', 'Content', 'en', 'Active'),
(172, 'Dashboard.modules.content.name', 'Contenido', 'es', 'Active'),
(173, 'Dashboard.modules.content.create', 'Add Content', 'en', 'Active'),
(174, 'Dashboard.modules.content.create', 'Agregar Contenido', 'es', 'Active'),
(175, 'Dashboard.table.name', 'Name', 'en', 'Active'),
(176, 'Dashboard.table.name', 'Nombre', 'es', 'Active'),
(177, 'Dashboard.table.value', 'Value', 'en', 'Active'),
(178, 'Dashboard.table.value', 'Valor', 'es', 'Active'),
(179, 'Dashboard.forms.fields.name', 'Name', 'en', 'Active'),
(180, 'Dashboard.forms.fields.name', 'Nombre', 'es', 'Active'),
(181, 'Dashboard.forms.fields.value', 'Value', 'en', 'Active'),
(182, 'Dashboard.forms.fields.value', 'Valor', 'es', 'Active'),
(183, 'Dashboard.modules.content.list', 'List of Content', 'en', 'Active'),
(184, 'Dashboard.modules.content.list', 'Lista de Contenidos', 'es', 'Active'),
(185, 'Dashboard.modules.pages.name', 'Pages', 'en', 'Active'),
(186, 'Dashboard.modules.content.messages.add.success', 'The content was added correctly', 'en', 'Active'),
(187, 'Dashboard.modules.pages.name', 'Páginas', 'es', 'Active'),
(188, 'Dashboard.modules.content.messages.add.success', 'El contenido fue agregado correctamente', 'es', 'Active'),
(189, 'Dashboard.modules.content.messages.update.success', 'The content was updated correctly', 'en', 'Active'),
(190, 'Dashboard.modules.content.messages.update.success', 'El contenido fue actualizado correctamente', 'es', 'Active'),
(191, 'Dashboard.modules.content.backup', 'Backup', 'en', 'Active'),
(192, 'Dashboard.modules.content.backup', 'Respaldar Contenido', 'es', 'Active'),
(193, 'Dashboard.modules.content.messages.add.fail', 'There was a problem trying to add the content', 'en', 'Active'),
(194, 'Dashboard.modules.content.messages.add.exists', 'This content already exists (try to change the language)', 'en', 'Active'),
(195, 'Dashboard.modules.content.messages.add.exists', 'Este contenido ya existe (intenta cambiar el idioma)', 'es', 'Active'),
(196, 'Dashboard.forms.fields.error.name', 'The key name is required', 'en', 'Active'),
(197, 'Dashboard.forms.fields.error.name', 'El nombre del contenido es requerido', 'es', 'Active'),
(198, 'Dashboard.forms.fields.error.value', 'The content value is required', 'en', 'Active'),
(199, 'Dashboard.forms.fields.error.value', 'El valor del contenido es requerido', 'es', 'Active'),
(200, 'Dashboard.modules.content.messages.add.fail', 'Hubo un problema al intentar agregar el contenido', 'es', 'Active'),
(201, 'Dashboard.modules.pages.list', 'List of Pages', 'en', 'Active'),
(202, 'Dashboard.modules.pages.list', 'Lista de Páginas', 'es', 'Active'),
(203, 'Dashboard.modules.pages.create', 'Create New Page', 'en', 'Active'),
(204, 'Dashboard.modules.pages.create', 'Crear Nueva Página', 'es', 'Active'),
(205, 'Dashboard.modules.pages.messages.add.fail', 'There was a problem trying to create the page', 'en', 'Active'),
(206, 'Dashboard.modules.pages.messages.add.fail', 'Hubo un problema al intentar crear la página', 'es', 'Active'),
(207, 'Dashboard.modules.pages.messages.add.exists', 'This page already exists (try to change the language)', 'en', 'Active'),
(208, 'Dashboard.modules.pages.messages.add.exists', 'Esta página ya existe (intenta cambiar el idioma)', 'es', 'Active'),
(209, 'Dashboard.modules.pages.messages.update.success', 'The page was updated correctly', 'en', 'Active'),
(210, 'Dashboard.modules.pages.messages.update.success', 'La página fue actualizada correctamente', 'es', 'Active'),
(211, 'Header.signIn.label', 'Sign In', 'en', 'Active'),
(212, 'Header.signIn.label', 'Registro', 'es', 'Active'),
(213, 'Dashboard.modules.configuration.list', 'Configuration', 'en', 'Active'),
(214, 'Dashboard.modules.configuration.list', 'Configuración', 'es', 'Active'),
(215, 'Dashboard.table.theme', 'Theme', 'en', 'Active'),
(216, 'Dashboard.table.theme', 'Diseño', 'es', 'Active'),
(217, 'Dashboard.table.application', 'Main Application', 'en', 'Active'),
(218, 'Dashboard.table.application', 'Aplicación Principal', 'es', 'Active'),
(219, 'Dashboard.forms.fields.theme', 'Theme', 'en', 'Active'),
(220, 'Dashboard.forms.fields.theme', 'Diseño', 'es', 'Active'),
(221, 'Dashboard.forms.fields.email', 'Email', 'en', 'Active'),
(222, 'Dashboard.forms.fields.email', 'Correo Electrónico', 'es', 'Active'),
(223, 'Dashboard.forms.fields.application', 'Main Application', 'en', 'Active'),
(224, 'Dashboard.forms.fields.application', 'Aplicación Principal', 'es', 'Active'),
(225, 'Dashboard.forms.fields.languages', 'Available Languages', 'en', 'Active'),
(226, 'Dashboard.forms.fields.languages', 'Idiomas Disponibles', 'es', 'Active'),
(227, 'Dashboard.forms.fields.comments', 'Comments Validation', 'en', 'Active'),
(228, 'Dashboard.forms.fields.comments', 'Validación de Comentarios', 'es', 'Active'),
(229, 'Dashboard.modules.configuration.name', 'Configuración', 'es', 'Active'),
(230, 'Dashboard.modules.configuration.messages.update.success', 'The configuration was updated correctly', 'en', 'Active'),
(231, 'Dashboard.modules.configuration.messages.update.success', 'La configuración fue actualizada correctamente', 'es', 'Active'),
(232, 'Dashboard.modules.configuration.name', 'Configuration', 'en', 'Active');
